-- MySQL Script generated by MySQL Workbench
-- Mon Feb 27 10:01:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Projetweb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Projetweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Projetweb` DEFAULT CHARACTER SET utf8 ;
USE `Projetweb` ;

-- -----------------------------------------------------
-- Table `Projetweb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projetweb`.`Client` (
  `CINClient` INT NOT NULL,
  `NomClient` VARCHAR(45) NULL,
  `PrénomClient` VARCHAR(45) NULL,
  `E-mailClient` VARCHAR(45) NULL,
  `MdpClient` VARCHAR(45) NULL,
  PRIMARY KEY (`CINClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projetweb`.`Propriétaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projetweb`.`Propriétaire` (
  `CINPropriétaire` INT NOT NULL,
  `NomPropriétaire` VARCHAR(45) NULL,
  `PrénomPropriétaire` VARCHAR(45) NULL,
  `E-mailPropriétaire` VARCHAR(45) NULL,
  `MdpPropriétaire` VARCHAR(45) NULL,
  PRIMARY KEY (`CINPropriétaire`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projetweb`.`Immobilier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projetweb`.`Immobilier` (
  `idImmobilier` INT NOT NULL,
  `NumEtage` INT NULL,
  `Equipement` VARCHAR(45) NULL,
  `Prix` DOUBLE NULL,
  `Description` VARCHAR(45) NULL,
  `Type` VARCHAR(45) NULL,
  `Propriétaire_CINPropriétaire` INT NOT NULL,
  PRIMARY KEY (`idImmobilier`),
  CONSTRAINT `fk_Appartement_Locataire1`
    FOREIGN KEY (`Propriétaire_CINPropriétaire`)
    REFERENCES `Projetweb`.`Propriétaire` (`CINPropriétaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Appartement_Locataire1_idx` ON `Projetweb`.`Immobilier` (`Propriétaire_CINPropriétaire` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Projetweb`.`Réservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projetweb`.`Réservation` (
  `idRéservation` INT NOT NULL,
  `DateArrivée` DATE NULL,
  `DateDépart` DATE NULL,
  `Immobilier_idImmobilier` INT NOT NULL,
  `Client_CINClient` INT NOT NULL,
  PRIMARY KEY (`idRéservation`),
  CONSTRAINT `fk_Réservation_Appartement1`
    FOREIGN KEY (`Immobilier_idImmobilier`)
    REFERENCES `Projetweb`.`Immobilier` (`idImmobilier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Réservation_Client1`
    FOREIGN KEY (`Client_CINClient`)
    REFERENCES `Projetweb`.`Client` (`CINClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idRéservation` ON `Projetweb`.`Réservation` (`idRéservation` ASC) INVISIBLE;

CREATE INDEX `fk_Réservation_Appartement1_idx` ON `Projetweb`.`Réservation` (`Immobilier_idImmobilier` ASC) VISIBLE;

CREATE INDEX `fk_Réservation_Client1_idx` ON `Projetweb`.`Réservation` (`Client_CINClient` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
